### ISSUE TITLE
Transaction Info (and expanded mode: Full Transaction Info)

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/bank-wallet-ios#58]
The share button should share permanent IPFS permalink to transaction record

![status pending](https://user-images.githubusercontent.com/42367908/45355405-22730600-b5e2-11e8-8849-c1c268c0df29.png)
![status processing](https://user-images.githubusercontent.com/42367908/45355406-22730600-b5e2-11e8-85a0-4e5d3b3bc9d7.png)
![status completed](https://user-images.githubusercontent.com/42367908/45355408-230b9c80-b5e2-11e8-9e2c-51fa131d6c86.png)

zpl://screen?sid=5b96439b0c99e06799f35cf9&pid=5b167c731d079e4122e946b7
zpl://screen?sid=5b9640560335644184df2f60&pid=5b167c731d079e4122e946b7
zpl://screen?sid=5b964054183ac85afe217de2&pid=5b167c731d079e4122e946b7

**Comment by esengulov** [comment]
@TalgatNurdinov review native iOS stocks app. Clicking on some stock loads relevant data about the asset in the bottom sheet controller. I would like to experiment with the same approach for Full Transaction Info.

When user clicks on More button below Payment Status in TX info bottom sheet, it should expand to  scrollable state allowing user to review all transaction related data that are not shown in the collapsed state. 

For reference refer to native iOS Stocks app (iOS version > 11)

Considerations:

- place More button instead of Close button
- move close button to the top right corner of the controller.

Expanded State:

1- stored in block: (that number should be a link, in the future it will open block explorer)
2- current block: 123
// place text below these two cells "Ex: A Bitcoin transaction considered completed (permanent) if 6 blocks has passed after the block where transaction is stored."


3- tranaction fee
4- transaction inputs: 
-- input ID 1 : amount1
-- input ID2 : amount2
-- ....
5- transaction outputs (in most case there will be just two items)
-- output ID1: amount1
--  output ID2: amount2
-- ...
6- Share button/text
